version: "3.8"

services:
  app-client:
    build: Frontend/Angular/Dockerfile
    ports:
    - "3001:3000"
    volumes:
      - .:/app/
    command: tail -f /dev/null
  app-server:
    build: Backend/NodeJS/Dockerfile
    ports:
    - "3000:3000"
    volumes:
      - .:/app/
    command: tail -f /dev/null
  db:
    image: mongodb
    